baseURL = 'https://kumaran-14.github.io/blog'
languageCode = 'en-us'
title = "Kumaran's Blog"
theme = 'paperesque'

[params]
  math = true

[[params.topmenu]]
  name = "Posts"
  url = "posts/"
[[params.topmenu]]
  name = "About"
  url = "about/"
[[params.topmenu]]
  name = "Resume"
  url = "resume/"
[[params.topmenu]]
  name = "Contact"
  url = "contact/"
[[params.topmenu]]
  name = "tags"
  url = "tags/"
[[params.topmenu]]
  name = "rss"
  url = "rss/"

[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  inline = [['$', '$'], ['\(', '\)']]
  block = [['$$', '$$'], ['\[', '\]']]

[markup.goldmark.renderer]
unsafe= true
